# from tkinter import*
# root=Tk()
# mymenu= Menu(root)
# root.config(menu=mymenu)
# submenu=Menu(mymenu)
# mymenu.add_cascade(label="File",menu=submenu)
# submenu.add_command(label='New file')
# submenu.add_command(label='Open file')
# submenu.add_separator()
# submenu.add_command(label='Open folder')
# submenu.add_command(label='Save')
# newmenu=Menu(mymenu)
# mymenu.add_cascade(label="Edit",menu=newmenu)
# newmenu.add_command(label='Undo')
# newmenu.add_command(label='Redo')
# newmenu.add_separator()
# newmenu.add_command(label='Cut')
# newmenu.add_command(label='Copy')
# newmenu.add_command(label='Paste')
# newonemenu=Menu(mymenu)
# mymenu.add_cascade(label="View",menu=newonemenu)
# newonemenu.add_command(label='Command pallette')
# newonemenu.add_command(label='Open view')
# newonemenu.add_separator()
# newonemenu.add_command(label='Appearence')
# newonemenu.add_command(label='Editor')
# root.mainloop()


"""toolbar and statusbar"""
from tkinter import*
root=Tk()
toolbar=Frame(root,bg='blue')
btn1=Button(toolbar,text='crop')
btn1.pack(side=LEFT,padx=2,pady=2)
btn2=Button(toolbar,text='add')
btn2.pack(side=RIGHT,padx=2,pady=2)
toolbar.pack(fill='x',side=TOP)
statusbar=Label(root,text='this is status bar',bd=2,anchor=W,bg='RED',fg='white')
statusbar.pack(fill='x',side=BOTTOM)
root.mainloop()

